import assert from 'node:assert/strict';
await import('../assets/review-features.js');
await import('../assets/api-normalizers.js');
const F=globalThis.ITUS_FEATURES;
assert.deepEqual(F.typesFor({role:'master'}),['new_messages']);
assert.deepEqual(F.typesFor({role:'executor'}),['executor_assigned']);
assert.deepEqual(F.typesFor({role:'tech'}),['quality_control_requested']);
assert.deepEqual(F.typesFor({role:'unknown'}),[]);
assert.deepEqual(F.typesFor({roles:['master','tech']}),['new_messages','quality_control_requested']);
assert.equal(F.unread({unreadMessagesCount:0}),0);
assert.equal(F.unread({}),null);
assert.equal(F.unread({unreadCount:-2}),null);
globalThis.ITUS_CONFIG={DISPLAY_TIME_ZONE:'Asia/Yekaterinburg'};
assert.equal(F.dateTime('2026-09-24T09:10:15Z'),'24.09.2026, 14:10');
assert.equal(F.dateTime('2026-09-24T14:10:15+05:00'),'24.09.2026, 14:10');
assert.equal(F.dateTime(''), '');
assert.equal(F.dateTime('unknown'),'unknown');
assert.equal(globalThis.ITUS_API.normalizeUser([{name:'Иван'},{role:{code:'master',name:'МП'}}]).name,'Иван');
console.log('Review features: role filters, counters, date conversion, user normalization OK');
